### ISSUE TITLE
Tile placement not working or working not in the correct position

### ISSUE THREAD

**Issue by OZadok** [opensource-ninjas/tower-defense#15]
see title.

**Comment by Coder-DG** [comment]
Title is unclear. Is this a bug, a feature, a test? If it's a test then you can add an "Add tests" issue and start piling up tests there.

**Comment by ghost** [comment]
It's a bug, when you choose a tower and try to place it in a tile, it may be placed in a different tile instead.

**Comment by Coder-DG** [comment]
The title is still unclear, you might want to write "Choosing a tower and trying to place it in a tile, sometimes places it in a different tile" and then label it as "bug".

**Comment by Coder-DG** [comment]
How do we reproduce this?
